name: tmiwork 
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyter
  - jupyterlab
# - jupyterlab-variableinspector
  - ipython
  - ipympl
  - nodejs
  - netcdf4
  - matplotlib
  - numpy
  - pandas
  - xarray
  - scipy
